bind-address = "0.0.0.0"
reporting-disabled = false

[logging]
level  = "info"
file   = "/opt/influxdb/shared/log.txt"

[admin]
port   = 8083

[api]
port     = 8086
read-timeout = "5s"

[input_plugins]

  [input_plugins.graphite]
  enabled = true
  address = "0.0.0.0"
  port = 2003
  database = "graphite"  # store graphite data in this database
  udp_enabled = true # enable udp interface on the same port as the tcp interface

  [input_plugins.collectd]
  enabled = false

  [input_plugins.udp]
  enabled = false
  # port = 4444
  # database = ""

  [[input_plugins.udp_servers]]
  enabled = false

# Raft configuration
[raft]
port = 8090
dir  = "/opt/influxdb/shared/data/raft"
debug = false

[storage]
dir = "/opt/influxdb/shared/data/db"
write-buffer-size = 10000
default-engine = "leveldb"
max-open-shards = 0
point-batch-size = 100
write-batch-size = 5000000
retention-sweep-period = "10m"

[storage.engines.leveldb]
max-open-files = 1000
lru-cache-size = "200m"

[storage.engines.rocksdb]
max-open-files = 1000
lru-cache-size = "200m"

[storage.engines.hyperleveldb]
max-open-files = 1000
lru-cache-size = "200m"

[storage.engines.lmdb]
map-size = "100g"

[cluster]
protobuf_port = 8099
protobuf_timeout = "2s" # the write timeout on the protobuf conn any duration parseable by time.ParseDuration
protobuf_heartbeat = "200ms" # the heartbeat interval between the servers. must be parseable by time.ParseDuration
protobuf_min_backoff = "1s" # the minimum backoff after a failed heartbeat attempt
protobuf_max_backoff = "10s" # the maxmimum backoff after a failed heartbeat attempt
write-buffer-size = 1000
max-response-buffer-size = 100
concurrent-shard-query-limit = 10

[wal]
dir   = "/opt/influxdb/shared/data/wal"
flush-after = 1000 # the number of writes after which wal will be flushed, 0 for flushing on every write
bookmark-after = 1000 # the number of writes after which a bookmark will be created
index-after = 1000
requests-per-logfile = 10000